//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroplandWpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<ResourceDictionary xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentat" +
            "ion\"\r\n                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"" +
            ">\r\n</ResourceDictionary>")]
        public string xamlToolTipsVisibilityDictionary {
            get {
                return ((string)(this["xamlToolTipsVisibilityDictionary"]));
            }
            set {
                this["xamlToolTipsVisibilityDictionary"] = value;
            }
        }
    }
}
